# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('comment', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('gw_address', models.CharField(max_length=32)),
                ('depaer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vpn.Depa')),
            ],
        ),
    ]
