# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-24 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0002_auto_20180522_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Netaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addrname', models.CharField(max_length=16)),
                ('gw_addrname', models.CharField(max_length=16)),
                ('flag', models.BooleanField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='useinfo',
            name='gw_address',
        ),
        migrations.AlterField(
            model_name='useinfo',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vpn.Netaddress'),
        ),
    ]
